name: Linux

on: [push, pull_request]
permissions:
  contents: write
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: 下载submodule源码
      run: mv -f .gitmodules_github .gitmodules && git submodule sync && git submodule update --init

    - name: apt-get安装依赖库(非必选)
      run: sudo apt-get update && sudo apt-get install -y cmake libssl-dev libsdl-dev libavcodec-dev libavutil-dev libswscale-dev libresample-dev libusrsctp-dev

    - name: 下载 SRTP
      uses: actions/checkout@v2
      with:
        repository: cisco/libsrtp
        fetch-depth: 1
        ref: v2.3.0
        path: 3rdpart/libsrtp

    - name: 编译 SRTP
      run: cd 3rdpart/libsrtp && ./configure --enable-openssl && make -j4 && sudo make install

    - name: 编译
      run: mkdir -p linux_build && cd linux_build && cmake .. -DENABLE_WEBRTC=true -DENABLE_FFMPEG=true && make -j $(nproc)

    - name: 运行MediaServer
      run: pwd && cd release/linux/Debug && sudo ./MediaServer -d &

    - name: generate openapi
      if: github.ref == 'refs/heads/master'
      run: cd tools/openapi && python3 generates.py install-dependencies

    - name: Commit and push if ./www/swagger/openapi.json changed
      if: github.ref == 'refs/heads/master'
      run: |
          git diff --exit-code ./www/swagger/openapi.json || (
          git config user.name alexliyu7352
          git config user.email liyu7352@gmail.com
          git add ./www/swagger/openapi.json
          git commit -m "update openapi.json"
          git push origin HEAD:master
          )

      
